### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by keren03** [ryanoutcome20/garrysmod-ddos#1]
Not quite understood, through lua executor does not work, throwing just in addons does not work. How to use it?

**Comment by ryanoutcome20** [comment]
> Not quite understood, through lua executor does not work, throwing just in addons does not work. How to use it?

Sorry for the late reply; you need to execute it in menustate. I recommend using interstate or similar executors to execute it, although you can just toss it into one of the menustate files.  Also, you wouldn't ever put this into an addon, it's not made for servers and you can't run menustate in an addon without rewriting the menustate files anyway.

Scroll down until you see "Menu" and read about it here:
https://wiki.facepunch.com/gmod/States
